---
title: "STAT463 Project: Sleep Health and Lifestyle"
author: "Lisa Lu 31088272"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(stringr)
```

# Data Exploration
```{r}
# Read in dataset
dataset <- read.table("Sleep_health_and_lifestyle_dataset.csv", 
                      header = TRUE, sep = ',', na.strings = "na")

# Print the first few rows of data frame
head(dataset)

# Explore the structure of the dataset
str(dataset)

# Get a descriptive statistics
summary(dataset)

# Data preprocessing
# Split Blood Pressure column into systolic and diastolic pressure as numeric data
dataset[c('Systolic.Pressure', 'Diastolic.Pressure')] <- as.numeric(str_split_fixed(dataset$Blood.Pressure, '/', 2))

# Combine "Normal" and "Normal Weight" values in BMI.Category
dataset$BMI.Category[dataset$BMI.Category == "Normal Weight"] <- "Normal"

# Convert stress level as factors
# categorical.data$Stress.Level <- as.factor(dataset$Stress.Level)


# Separate categorical and numeric data
categorical.data <- dataset[,c("Gender","Occupation", "BMI.Category", "Sleep.Disorder" )]
numeric.data <- dataset[,c(3,5,6,7,8,11,12,14,15)]

# Plot the data -- Histogram

# Frequency chart
par(mfrow = c(4,3))

dataset %>% 
  ggplot(aes(x = Gender)) +
  geom_bar() +
  labs(y = "Frequency", x = "Gender")

dataset %>% 
  ggplot(aes(x = Age)) +
  geom_bar() +
  labs(y = "Frequency", x = "Age")

dataset %>% 
  ggplot(aes(y = Occupation)) +
  geom_bar() +
  labs(y = "Occupation", x = "Frequency")

dataset %>% 
  ggplot(aes(x = Sleep.Duration)) +
  geom_bar() +
  labs(y = "Frequency", x = "Sleep Duration")

dataset %>% 
  ggplot(aes(x = Quality.of.Sleep)) +
  geom_bar() +
  labs(y = "Frequency", x = "Quality of Sleep")

dataset %>% 
  ggplot(aes(x = Physical.Activity.Level)) +
  geom_bar() +
  labs(y = "Frequency", x = "Physical Activity Level")

dataset %>% 
  ggplot(aes(x = Stress.Level)) +
  geom_bar() +
  labs(y = "Frequency", x = "Stress Level")

dataset %>% 
  ggplot(aes(x = BMI.Category)) +
  geom_bar() +
  labs(y = "Frequency", x = "BMI Category")

dataset %>% 
  ggplot(aes(x = Heart.Rate)) +
  geom_bar() +
  labs(y = "Frequency", x = "Heart Rate")

dataset %>% 
  ggplot(aes(x = Daily.Steps)) +
  geom_bar() +
  labs(y = "Frequency", x = "Daily Steps")

dataset %>% 
  ggplot(aes(x = Sleep.Disorder)) +
  geom_bar() +
  labs(y = "Frequency", x = "Sleep Disorder")

dataset %>% 
  ggplot(aes(x =Systolic.Pressure)) +
  geom_bar() +
  labs(y = "Frequency", x = "Systolic Pressure")

dataset %>% 
  ggplot(aes(x = Diastolic.Pressure)) +
  geom_bar() +
  labs(y = "Frequency", x = "Diastolic Pressure")


```


# Explore the factors affecting quality of sleep
```{r}
# Use linear regression model
sleep <- dataset[, -c(1, 10)]
# Get the full multiple linear regression model
lr_full <- lm(Quality.of.Sleep ~ Age + Gender + Occupation + Sleep.Duration + Physical.Activity.Level + Stress.Level + Heart.Rate + Daily.Steps + Systolic.Pressure + Diastolic.Pressure + BMI.Category, data = dataset)

summary(lr_full)

plot(lr_full)
lr_backward <- step(lr_full, direction = "backward")
summary(lr_backward)

 # Use PCA analysis
# Standardise the Quality of sleep and stress level
Quality.of.Sleep <- data.frame(scale(dataset$Quality.of.Sleep))
Stress.Level <- data.frame(scale(dataset$Stress.Level))
Physical.Level <-data.frame(scale(dataset$Physical.Activity.Level))

pca_dataset <- select(dataset, Age, Physical.Activity.Level, Stress.Level, Sleep.Duration, Heart.Rate, Daily.Steps, Systolic.Pressure, Diastolic.Pressure)
pca <- prcomp(scale(pca_dataset))
screeplot(pca)
summary(pca)
pca$rotation
biplot(pca)
```

```{r}
step.model <- step(lr_full, direction = "backward")
summary(step.model)
```


# Explore the causes of sleep disorder
```{r}
# Multinomial Logistic Regression: predict the probablities of categorically dependent variable
library(nnet)
mlr <- multinom(Sleep.Disorder ~ Gender + Occupation + Stress.Level + Physical.Activity.Level, data = sleep)
summary(mlr)
exp(summary(mlr)$coefficients)
step(mlr, direction = 'backward')

```

# Generalised Linear Mixed Model
```{r}
library(lme4)
m1 <- lmer(Quality.of.Sleep ~ Sleep.Duration + Stress.Level + (1|Occupation), data = sleep)
summary(m1)
m2 <- lmer(Quality.of.Sleep ~ Sleep.Duration + (1|Occupation), data=sleep)
summary(m2)
```

